Implement select command
AY2021S2-CS2103T-T12-3/tp pull request #119
Opened 2021-03-25 11:04 UTC by yaowei-soc

2021-03-30 14:04 UTC, tanboonji requested changes
In the implementation of the feature, the model stores a list of ```Person``` who is selected. However, this list is not linked to the actual ```Person``` list in the Address Book and therefore is not updated whenever a ```Person``` is updated or deleted in the actual list.

This causes a weird behaviour to occur in the UI whenever a person is updated or deleted. One example (image attached below) would be when I selected ```Yao Wei```, deleted it and added ```Yao Wei``` again. This causes the new ```Yao Wei``` to still be selected.

![select_bug](https://user-images.githubusercontent.com/12221867/113001570-80b56380-91a3-11eb-9cc6-a7a077f6d5b8.gif)

Possible issues may arise when implementing bulk action commands (such as edit and delete) with the selected ```Person``` list as well.

2021-03-31 08:11 UTC, oeiyiping requested changes
Some minor docs-related issues, with a major bug as shown below.

Major bug: bulk delete/edit via `shown` keyword will apply changes to all entries.

`delete shown`:
![select 1 2 3](https://user-images.githubusercontent.com/70749318/113112285-98d8c180-923b-11eb-8761-ef2798397cd9.png)
![delete shown](https://user-images.githubusercontent.com/70749318/113112302-9d04df00-923b-11eb-9a03-06dd0eb8019d.png)

`edit shown`:
![select 1 2](https://user-images.githubusercontent.com/70749318/113112370-aee68200-923b-11eb-9d9b-10590d740962.png)
![edit shown -e barney@dinosaur com](https://user-images.githubusercontent.com/70749318/113112377-b0b04580-923b-11eb-8ef4-d5a89444f117.png)

2021-03-31 08:11 UTC, oeiyiping commented on docs/UserGuide.md
> +The selected person will have a highlighted index number to indicate selection status.
Might be good to specify highlight to be green, since specificity helps a lot in UG.

2021-03-31 08:11 UTC, oeiyiping commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +            + "Parameters: INDEX [INDEX…] (must be a valid positive integer)\n"
Same slight formatting issue for [INDEX...] as mentioned.

2021-03-31 08:11 UTC, oeiyiping commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +    public static final String MESSAGE_DELETE_PERSONS_SUCCESS = "Deleted multiple person:\n%1$s";
Slight grammar issue: return message should include persons instead.

2021-03-31 08:48 UTC, yaowei-soc commented on docs/UserGuide.md
> +**Format**: `delete INDEX [INDEX…]`
I think it should be in this format. See: https://developers.google.com/style/code-syntax

2021-03-31 08:48 UTC, yaowei-soc commented on docs/UserGuide.md
> +* Deletes the person at the specified `INDEX` or `[INDEX…]`.
I think it should be in this format. See: https://developers.google.com/style/code-syntax

2021-03-31 08:54 UTC, oeiyiping commented on docs/UserGuide.md
> +**Format**: `delete INDEX [INDEX…]`
![image](https://user-images.githubusercontent.com/70749318/113117994-98432980-9241-11eb-9da2-0ef098ff4598.png)
Oh okay, I was referencing this clause in our UG.

2021-03-31 09:08 UTC, yaowei-soc commented on docs/UserGuide.md
> +**Format**: `delete INDEX [INDEX…]`
I think `[-t TAG]...` means you can have multiple tag flags while `[-t TAG...]` will mean you can have only one tag flag but multiple "arguments" after that.

2021-03-31 09:54 UTC, oeiyiping commented on docs/UserGuide.md
> +**Format**: `delete INDEX [INDEX…]`
That makes sense, I think original notation [INDEX…] should be fine, as long as it is explained what that means in the UG.

2021-03-31 11:58 UTC, justgnohUG reviewed
Just a suggestion, perhaps for future reference, would it be better to highlight the whole card as seen in the blue highlight of a Person Card? 

PS: Interesting usage of JavaFX PseudoClass

![image](https://user-images.githubusercontent.com/77429783/113140666-4e673d00-925b-11eb-9c69-915db04186b1.png)

2021-03-31 13:53 UTC, yaowei-soc commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +            + "Parameters: INDEX [INDEX…] (must be a valid positive integer)\n"
Updated in latest commit. Do check it out.

2021-03-31 13:54 UTC, yaowei-soc commented on docs/UserGuide.md
> +or `delete shown` to delete all the shown person.
Updated in latest commit. Do check it out.

2021-03-31 13:56 UTC, yaowei-soc commented on docs/UserGuide.md
> +The selected person will have a highlighted index number to indicate selection status.
For this, there is an image indicating that it is highlighted. Do you want it to be listed here?

2021-03-31 13:58 UTC, yaowei-soc commented on src/main/java/seedu/address/logic/commands/DeleteCommand.java
> +    public static final String MESSAGE_DELETE_PERSONS_SUCCESS = "Deleted multiple person:\n%1$s";
Updated in latest commit. Do check it out.

2021-03-31 14:00 UTC, yaowei-soc commented
> 
> 
> Just a suggestion, perhaps for future reference, would it be better to highlight the whole card as seen in the blue highlight of a Person Card?
> 
> PS: Interesting usage of JavaFX PseudoClass
> 
> ![image](https://user-images.githubusercontent.com/77429783/113140666-4e673d00-925b-11eb-9c69-915db04186b1.png)

I was thinking of doing that, however I feel that it may conflict (visually) with the active state. Maybe we could add in a new icon somewhere to indicate that selection status?

2021-03-31 14:06 UTC, oeiyiping commented on docs/UserGuide.md
> +The selected person will have a highlighted index number to indicate selection status.
That's fine then, the image should do the job well too.

2021-03-31 14:07 UTC, oeiyiping commented on docs/UserGuide.md
> +* Deletes the person at the specified `INDEX` or `[INDEX…]`.
Yeap looks good to me!

2021-03-31 14:12 UTC, oeiyiping approved these changes
LGTM!

2021-03-31 15:54 UTC, darkdestry-t approved these changes
Might be worth moving the special index parsing code to utils but since this is the "last milestone" for features I think we are good here. LGTM.

2021-03-31 15:55 UTC, merged