Autofill flags for some commands
AY2021S2-CS2103T-T12-3/tp pull request #124
Opened 2021-03-28 09:09 UTC by justgnohUG

Notable Changes:
- Fix UI bug for index_out_of_bounds in Person List Panel
- Add auto-filling off flags for "ADD" command

Todos:
- [ ] Filter Command
- [ ] Tests
- [ ] JavaDoc
- [ ] UG
- [ ] DG

2021-03-31 09:37 UTC, yaowei-soc requested changes
`fi <tab>` works
`e <tab>` doesn't work
`a <tab>` doesn't work

![ohmy](https://user-images.githubusercontent.com/77482180/113124054-b744ba00-9247-11eb-83d6-a8cc029e4c07.gif)

2021-03-31 14:22 UTC, yaowei-soc commented
While test @ commit 72cdf3e623021fb07025ad089c1f9dfd58f05bb7, I found some bugs

1: Is the `find` command supposed to be deleted in this scenario?
![ohmy1](https://user-images.githubusercontent.com/77482180/113159673-62b53500-926f-11eb-8cc7-72b0968361a3.gif)

2: Does the autocomplete allow me to cycle through the flags?
![ohmy2](https://user-images.githubusercontent.com/77482180/113159855-85474e00-926f-11eb-80f0-18b734191fc9.gif)

2021-04-01 03:02 UTC, oeiyiping approved these changes

2021-04-01 03:14 UTC, oeiyiping approved these changes
Other than the (very) slight issue, LGTM w.r.t docs

2021-04-01 03:14 UTC, oeiyiping commented on docs/UserGuide.md
> +| `Other Commands`| [Coming Soon] |
Not sure if this was intended, but the `Other Commands | coming soon` is not in its own row.

2021-04-01 03:41 UTC, justgnohUG commented on docs/UserGuide.md
> +| `Other Commands`| [Coming Soon] |
Yes it is intentional. Thanks for pointing that out.

2021-04-01 10:12 UTC, yaowei-soc reviewed
Latest commits seem to have solved the issues I found earlier. May want to check the current review comments.

2021-04-01 10:12 UTC, yaowei-soc commented on src/main/java/seedu/address/ui/MainWindow.java
> +                                    currentList = availFlags;
Possible code quality issue here, deep nesting: https://nus-cs2103-ay2021s2.github.io/website/se-book-adapted/chapters/codeQuality.html#avoid-complicated-expressions

2021-04-01 10:12 UTC, yaowei-soc commented on docs/UserGuide.md
> +| `add`                       | `-n` , `-p`, `-e`, `-a`, `-r`, `-t` |
While following the user guide for `add` followed by tab, I found out that auto complete only works if I have a space. Might need to highlight that in.

![ohmy3](https://user-images.githubusercontent.com/77482180/113279382-98145e00-9315-11eb-996e-ab14c95f8fd2.gif)

2021-04-01 10:38 UTC, justgnohUG commented on docs/UserGuide.md
> +| `add`                       | `-n` , `-p`, `-e`, `-a`, `-r`, `-t` |
Added a note in dev@c5811ce.

2021-04-01 11:08 UTC, justgnohUG commented on src/main/java/seedu/address/ui/MainWindow.java
> +                                    currentList = availFlags;
As there are quite a few moving parts for the toggling of flags (e.g Command Box, logic, currentList, lastFlag), I'll still need some time to think about how to un-nest this portion. 

Small reduction in code in dc2e88d

2021-04-01 11:54 UTC, tanboonji commented
Autofill for ```edit``` is not working on my side.

![edit_bug](https://user-images.githubusercontent.com/12221867/113290104-bc773700-9323-11eb-94ac-bf1cbfd45670.gif)

2021-04-01 13:50 UTC, tanboonji requested changes
Other than the commented issues and the possible deep nesting as mentioned by @yaowei-soc, the rest of the code LGTM.

2021-04-01 13:50 UTC, tanboonji commented on src/main/java/seedu/address/logic/LogicManager.java
> +        flags.removeIf(f -> currentStrings.contains(f));
This lambda expression can be replaced with method reference ```flags.removeIf(currentStrings::contains)```

2021-04-01 13:50 UTC, tanboonji commented on src/main/java/seedu/address/logic/LogicManager.java
> +        if (commandStrings.length() == 0 || commandStrings == null) {
```commandStrings == null``` is unreachable. The reason is because if ```commandStrings``` is ```null```, a NullPointerException would have been thrown when you called ```commandStrings.length()```.

Therefore ```commandStrings == null``` should be checked first before you check ```commandStrings.length() == 0```.

2021-04-01 13:50 UTC, tanboonji commented on src/main/java/seedu/address/logic/LogicManager.java
> +        }
I don't think you need to split the ```commandStrings``` in line 197.

You can just call ```commandStrings.startsWith(AddCommand.COMMAND_WORD)``` and it will still work.

2021-04-01 13:50 UTC, tanboonji commented on src/main/java/seedu/address/logic/LogicManager.java
> +        String command = commandStrings.split("-")[0];
Same here, I do not think it is necessary to split the ```commandStrings``` here.

2021-04-01 13:50 UTC, tanboonji commented on src/main/java/seedu/address/logic/LogicManager.java
> +                Integer.parseInt(command.split("-")[0].replaceAll("\\D+", ""));
This way to extract the index could potentially be problematic. For example, ```edit 1 2 3 -n``` and ```edit ! 1 -n``` will be counted as a valid index because any non-digit characters will be removed and they will become ```123``` and ```1``` respectively.

I think a better way to deal with this would be to first split the command and command arguments using a ```Matcher```.
You can reference the ```AddressBookParser``` for example on how it separates the command and the arguments.

After which, you can depend on the ```ArgumentTokenizer``` to get the preamble which will be your index.

2021-04-01 13:50 UTC, tanboonji commented on src/main/java/seedu/address/ui/MainWindow.java
> +                        if (lastFlag.split(" ").length > 1 || lastFlag.equals("add ") || lastFlag.equals("edit ")) {
You should replace the magic literals here with ```AddCommand.COMMAND_WORD``` and ```EditCommand.COMMAND_WORD```.

2021-04-01 14:24 UTC, justgnohUG commented on src/main/java/seedu/address/logic/LogicManager.java
> +        flags.removeIf(f -> currentStrings.contains(f));
I chose not to convert it to that because it seemed quite verbose to me. I will change it. Thanks for pointing that out

2021-04-01 14:26 UTC, justgnohUG commented on src/main/java/seedu/address/logic/LogicManager.java
> +        if (commandStrings.length() == 0 || commandStrings == null) {
That makes sense. Thanks for suggestion.

2021-04-01 14:32 UTC, justgnohUG commented on src/main/java/seedu/address/logic/LogicManager.java
> +        String command = commandStrings.split("-")[0];
Removed command and it works.

2021-04-01 14:34 UTC, justgnohUG commented on src/main/java/seedu/address/logic/LogicManager.java
> +                Integer.parseInt(command.split("-")[0].replaceAll("\\D+", ""));
Alright I will need time to process this. I will set a "TODO" for now for v1.4.

2021-04-01 14:40 UTC, justgnohUG commented on src/main/java/seedu/address/ui/MainWindow.java
> +                        if (lastFlag.split(" ").length > 1 || lastFlag.equals("add ") || lastFlag.equals("edit ")) {
Very good point. Thank you.

2021-04-01 14:52 UTC, tanboonji approved these changes
LGTM

2021-04-01 14:55 UTC, yaowei-soc approved these changes
Didn't find any bugs while testing. LGTM

2021-04-01 14:57 UTC, merged