Add field specific and general search to find command
AY2021S2-CS2103T-T12-3/tp pull request #130
Opened 2021-03-29 12:00 UTC by darkdestry-t

Checklist before exitting draft:

- [ ] Code changes
- [ ] Documentation
- [ ] Test

Closes #7 #3 #91

2021-03-30 14:20 UTC, tanboonji requested changes
Two minor changes requested. Other than that, ```Logic``` and ```Docs``` LGTM.

2021-03-30 14:20 UTC, tanboonji commented on src/main/java/seedu/address/commons/util/StringUtil.java
> +     * using simple ration if data is shorter.
```ratio``` spelled as ```ration```.

2021-03-30 14:20 UTC, tanboonji commented on src/main/java/seedu/address/logic/parser/FindCommandParser.java
> +
Extra line breaks in lines 71-72 and 74-75.

2021-03-30 18:42 UTC, tanboonji approved these changes
LGTM

2021-03-30 20:16 UTC, yaowei-soc reviewed
Changes look good to me, however I have a pending question on the *KeywordsPredicate methods:
- EmailContainsKeywordsPredicate
- EmailContainsKeywordsPredicate
- RemarkContainsKeywordsPredicate
- TagContainsKeywordsPredicate

2021-03-30 20:16 UTC, yaowei-soc commented on src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
> +                && keywords.equals(((EmailContainsKeywordsPredicate) other).keywords)); // state check
Hmm using `.equals` would mean that ["first", "second"] would not be equals to ["second", "first"]. Is this an intended feature?

2021-03-31 07:00 UTC, oeiyiping approved these changes
Aside from the existing comments, LGTM.

2021-03-31 11:26 UTC, darkdestry-t commented on src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
> +                && keywords.equals(((EmailContainsKeywordsPredicate) other).keywords)); // state check
It isnt intended but has been the case for the original Name predicate. I think as a predicate its equal technically but shouldnt cause any issue if it isnt.

2021-03-31 17:22 UTC, darkdestry-t commented on src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
> +        assertParseSuccess(parser, " \n Alice \n \t Reception  \t", expectedFieldsFindCommand);
Non-issue. As comment says, white space is part of the test case.

2021-03-31 17:23 UTC, darkdestry-t commented on src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
> +        assertParseSuccess(parser, PREFIX_EMAIL + " \n test@mail.com \n \t bob@box.net  \t", expectedEmailFindCommand);
Fixed to put whitespace between prefix but not between keywords. The whitespace is part of test case

2021-03-31 17:23 UTC, darkdestry-t commented on src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
> +        assertParseSuccess(parser, PREFIX_REMARK + " \n HR \n \t Network  \t", expectedRemarkFindCommand);
Fixed to put whitespace between prefix but not between keywords. The whitespace is part of test case

2021-03-31 17:23 UTC, darkdestry-t commented on src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
> +        assertParseSuccess(parser, PREFIX_TAG + " \n Hotline \n \t Service  \t", expectedTagFindCommand);
Fixed to put whitespace between prefix but not between keywords. The whitespace is part of test case

2021-03-31 17:23 UTC, darkdestry-t commented on src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
> +        assertParseSuccess(parser, PREFIX_NAME + " \n Alice \n \t Bob  \t", expectedNameFindCommand);
Fixed to put whitespace between prefix but not between keywords. The whitespace is part of test case

2021-03-31 18:05 UTC, yaowei-soc approved these changes
LGTM

2021-03-31 18:06 UTC, merged