Remove sorted observableList from usage
AY2021S2-CS2103T-T12-3/tp pull request #207
Opened 2021-04-04 12:49 UTC by darkdestry-t

Removes sorted list

Resolves #205 

## Regression Test Required
@tanboonji @oeiyiping @justgnohUG @yaowei-soc 
Please perform verification on your own commands. Perform general testing as well as verify items in the bugs reported in PE-D. Remove the blocker label if resolved.

Issue List: https://github.com/AY2021S2-CS2103T-T12-3/tp/issues?q=is%3Aopen+is%3Aissue+label%3Ablocked+205+in%3Acomments

**General Test Structure outside of Issue verification**
1. Run program, execute command
2. Run program, execute find, execute command
3. Run program, execute list, execute command
4. Run program, execute find, execute list, execute command
5. Run program, execute list, execute find, execute command

## Checklist for merging

- [ ] Above Issue list is cleared
- [ ] Changes reviewed
- Modification commands verified to be working
  - [ ] Edit
  - [ ] Delete
  - [ ] Tag
  - [ ] Select

2021-04-05 19:09 UTC, yaowei-soc reviewed
Tested and can confirm that this PR fixes all the issues.

Have a small issue with the updated documentation in the UG.

2021-04-05 19:09 UTC, yaowei-soc commented on docs/UserGuide.md
> +* Results will be sorted in dictionary order.
Does this mean that the results will not be sorted by similarity anymore? Meaning that the order in which find returns will be based on the original order of the list?

If that is the case, I don't think "dictionary order" would be applicable here since [it means alphabetical order](https://en.wikipedia.org/wiki/Dictionary_order). Maybe not mentioning that the items will be sorted will be clearer?

2021-04-07 04:51 UTC, tanboonji commented on docs/UserGuide.md
> +* Results will be sorted in dictionary order.
I agree with @yaowei-soc, maybe saying `Results will be shown in alphabetical order` might be easier for the user to understand than saying `Results will be sorted in dictionary order`.

2021-04-10 11:50 UTC, tanboonji requested changes
Requested changes in UG based on my previous comment.

2021-04-11 05:45 UTC, darkdestry-t commented on docs/UserGuide.md
> +* Results will be sorted in dictionary order.
I removed that line completely. Theres actually no sorting. The sequence is whatever sequence you added the contact into the address book

2021-04-11 07:14 UTC, tanboonji commented on docs/UserGuide.md
> +* Results will be sorted in dictionary order.
Agree with that. Realised it is not sorted at all, but just coincidentally the default contacts in the address book are in alphabetical order.

2021-04-11 07:38 UTC, yaowei-soc approved these changes
LGTM

2021-04-11 08:39 UTC, darkdestry-t commented
Fixes #196 
Fixes #195 
Fixes #186 
Fixes #185 
Fixes #184 
Fixes #182 
Fixes #171 
Fixes #170 
Fixes #169 
Fixes #168 
Fixes #148 
Fixes #122

2021-04-11 08:39 UTC, tanboonji approved these changes
LGTM.

Tested with delete command, edit command, tag add & delete command and select command. 
Also test bulk delete, tag add & delete and bulk select command.

2021-04-11 09:03 UTC, oeiyiping approved these changes
LGTM.

2021-04-11 09:43 UTC, justgnohUG commented
LGTM

Tested with :
- `Nested Find` s (find -> find -> command), 
- Bulk Commands included
- Select Commands included

Autocomplete flags work as expected to be unaffected. Autocomplete commands work as expected too.

Verified that this PR resolves all issues as mentioned in previous comments.

2021-04-11 09:45 UTC, justgnohUG approved these changes

2021-04-11 09:55 UTC, merged