docs: update ReadMe.md
AY2021S2-CS2103T-T12-3/tp pull request #64
Opened 2021-03-05 06:41 UTC by justgnohUG

resolves #61

2021-03-05 06:59 UTC, yaowei-soc commented
LGTM, but perhaps might want to rename PR to something more appropriate. See #52

2021-03-05 07:05 UTC, justgnohUG commented
@yaowei-soc fixed PR naming convention to provide more context and information.

Thanks for the reference.

2021-03-05 09:54 UTC, yaowei-soc requested changes
![image](https://user-images.githubusercontent.com/77482180/110099066-d896bf80-7ddb-11eb-80ca-069ed667b9c2.png)

2021-03-05 09:54 UTC, yaowei-soc commented on README.md
> +## Setup
Trailing white space

2021-03-05 09:54 UTC, yaowei-soc commented on README.md
> +## Features
Trailing white space

2021-03-06 06:24 UTC, yaowei-soc approved these changes
LGTM

2021-03-06 06:25 UTC, merged