Add `filter` command to filter person list items
AY2021S2-CS2103T-T12-3/tp pull request #70
Opened 2021-03-09 18:15 UTC by yaowei-soc

Implementation: Add a new `filter` command to set which items are filtered out.

Name control cannot be filtered out.

`filter` without any arguments will by default show all controls.
`filter a/` will show only the address and name.

Tasks:

- [ ] Test cases
- [ ] Documentation (DG, UG)

Closes #13

2021-03-13 10:13 UTC, tanboonji reviewed
In ModelManager, should line 107
```updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);``` of 
```public void addPerson(Person person)``` method
be removed to ensure the filter is persistent even after adding a person?

Other than this, everything else LGTM for ```Logic``` component.

2021-03-13 10:37 UTC, yaowei-soc commented
> In ModelManager, should line 107
> `updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);` of
> `public void addPerson(Person person)` method
> be updated/removed to ensure the filter is persistent even after adding a person?
> 
> Other than this, everything else LGTM for `Logic` component.

This line should not affect the filter after adding a new person

2021-03-13 10:39 UTC, tanboonji commented
> > In ModelManager, should line 107
> > `updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS);` of
> > `public void addPerson(Person person)` method
> > be updated/removed to ensure the filter is persistent even after adding a person?
> > Other than this, everything else LGTM for `Logic` component.
> 
> This line should not affect the filter after adding a new person

Alright, LGTM.

2021-03-13 10:40 UTC, tanboonji approved these changes

2021-03-13 12:55 UTC, oeiyiping reviewed
Aside from that one comment on method header, everything regarding the code for `Model` and `Command` LGTM.

2021-03-13 12:55 UTC, oeiyiping commented on src/main/java/seedu/address/logic/Logic.java
> +     * @return predicate that returns true if prefix linked control should be hidden
Correct me if I'm wrong - DisplayFilterPredicate.test() will return true if field is specified, and only these specified fields will be set as visible and managed. If that is the case, can I clarify what you meant by "returns true (...) should be hidden"?

2021-03-13 13:08 UTC, yaowei-soc commented on src/main/java/seedu/address/logic/Logic.java
> +     * @return predicate that returns true if prefix linked control should be hidden
Ah yes, it should be true if it will be shown and false if it should be hidden.

What do you think of rephrasing it like this:

```
/**
 * Returns predicate that determines field control visibility.
 * @return predicate that returns true if prefix linked control should be shown
 */
```

2021-03-13 13:14 UTC, oeiyiping commented on src/main/java/seedu/address/logic/Logic.java
> +     * @return predicate that returns true if prefix linked control should be hidden
Looks good to me 👍

2021-03-14 06:40 UTC, darkdestry-t requested changes
I dont see any changes to storage. Giving my comments to unit tests and code coverage instead.

2021-03-14 06:40 UTC, darkdestry-t commented on src/test/java/seedu/address/logic/commands/FilterCommandTest.java
> +
Missing Equality Check test
```
command = 1 -> false
command = null -> false
command = new command of same parameter -> true
command = same command -> true
command = different command -> false
```

2021-03-14 06:40 UTC, darkdestry-t commented on src/test/java/seedu/address/model/DisplayFilterPredicateTest.java
> +    }
Missing checks
```
predicate = 1 -> false
predicate = null -> false
predicate = same predicate object -> true
```

2021-03-14 10:56 UTC, yaowei-soc commented on src/test/java/seedu/address/logic/commands/FilterCommandTest.java
> +
Added more test cases @ 1e159f4e080ebf9107aa3e93e24bb7c8b32d70a2

2021-03-14 10:56 UTC, yaowei-soc commented on src/test/java/seedu/address/model/DisplayFilterPredicateTest.java
> +    }
Added more test cases @ 1e159f4e080ebf9107aa3e93e24bb7c8b32d70a2

2021-03-14 13:11 UTC, oeiyiping approved these changes

2021-03-14 13:36 UTC, darkdestry-t commented on src/test/java/seedu/address/model/DisplayFilterPredicateTest.java
> +    }
You missed the Same object check

2021-03-14 13:55 UTC, yaowei-soc commented on src/test/java/seedu/address/model/DisplayFilterPredicateTest.java
> +    }
This line should be checking for same object

```java
    @Test
    public void test_predicateEqualsCheck_allEquals() {
         ...
         assertEquals(addressArgs, addressArgs);
         ...
```

https://github.com/AY2021S2-CS2103T-T12-3/tp/pull/70/commits/1e159f4e080ebf9107aa3e93e24bb7c8b32d70a2#diff-0d3609fd2c6dc142dc264b379879b18ceb04ec5efcd9e1ba87f410b4070f4b4aR47

2021-03-15 05:34 UTC, darkdestry-t commented on src/test/java/seedu/address/model/DisplayFilterPredicateTest.java
> +    }
Hmm not sure why test coverage missed it but I guess its fine.

2021-03-15 05:35 UTC, darkdestry-t approved these changes
Looks good now.

2021-03-15 09:22 UTC, justgnohUG approved these changes
Changes and rectifications LGTM.

2021-03-15 09:26 UTC, merged

2021-03-15 12:03 UTC, oeiyiping commented on src/main/java/seedu/address/model/Model.java
> +     * @param displayFilterPredicate that returns true if prefix linked control should be hidden
Just spotted this: "@param displayFilterPredicate that returns true if prefix linked control should be hidden",
looks to be the same mistake as befor (ie. returns true if (...) should be shown).

2021-03-15 12:04 UTC, oeiyiping commented on src/main/java/seedu/address/model/Model.java
> +     * @return predicate that returns true if prefix linked control should be hidden
Just spotted this: "@param displayFilterPredicate that returns true if prefix linked control should be hidden",
looks to be the same mistake as befor (ie. returns true if (...) should be shown).