feat: Add add alias and delete alias command
AY2021S2-CS2103T-T12-3/tp pull request #73
Opened 2021-03-13 10:28 UTC by tanboonji

Implementation: 

Add a new alias command to allow binding of commands to shorter aliases.
Alias command is split into three subcommands, ```alias add```, ```alias delete``` and ```alias list```.

Tasks (to be done before merge):

- [ ] List aliases
- [ ] Save aliases to the user local drive
- [ ] Load aliases from the local user drive
- [ ] Check if the command to be aliased is valid
- [ ] Test cases
- [ ] Documentation (DG, UG)

Closes #5

2021-03-16 09:46 UTC, oeiyiping reviewed
Aside from the comment on Command class, LGTM.

2021-03-16 09:46 UTC, oeiyiping commented on src/main/java/seedu/address/model/alias/Command.java
> +public class Command {
Correct me if I'm wrong - this Command class is different from the one in address/logic/commands right? There is one Command class in that path, so I'm not sure if having two classes of the same name would be confusing.

2021-03-16 17:40 UTC, justgnohUG commented on src/main/java/seedu/address/model/alias/Command.java
> +public class Command {
The one in address/logic/commands is an {abstract} class and exists in a different package from this Command.java. 

I think since they are clearly differentiable by file path, it shouldn't be an issue. Because alias/Command.java is named as such logically. 

"Paths (or URLs) are nice because they are nested identifiers."

Reference: https://softwareengineering.stackexchange.com/questions/250481/is-it-a-bad-practice-to-give-two-very-different-files-with-the-same-general-purp

2021-03-17 03:42 UTC, tanboonji commented on src/main/java/seedu/address/model/alias/Command.java
> +public class Command {
@oeiyiping I have actually pondered over this for some time, did some research and decided to use the same class name.

As mentioned by @justgnohUG, since they are clearly differentiable by file path, and on top of that, there is an extremely low possibility that you will be referencing both Command classes in another class, I don't see any issues.

Feel free to share your thoughts and opinions again.

2021-03-17 03:43 UTC, oeiyiping commented on src/main/java/seedu/address/model/alias/Command.java
> +public class Command {
Good point, thanks for the explanation. No problem here then.

2021-03-17 04:04 UTC, oeiyiping requested changes
Minor code quality issues as commented, otherwise LGTM.

2021-03-17 04:51 UTC, tanboonji commented on src/main/java/seedu/address/logic/commands/CommandResult.java
>      private final boolean exit;
For this, I followed the original AB3 boolean variable name ```showHelp``` and therefore named the boolean variable ```showAlias```.

How about changing both to ```shouldShowHelp```` and ```shouldShowAlias```?

2021-03-17 04:58 UTC, oeiyiping commented on src/main/java/seedu/address/logic/commands/CommandResult.java
>      private final boolean exit;
Your suggestion sounds good to me! 

I am aware that some of the pre-existing boolean variables from AB3 might not seem exactly comply with the textbook recommendation, and have thought about just leaving the variable names as is. However, I currently feel that it is better to err on the safe side, as it is always possible for the reviewer to argue that "just because it was originally named this way, doesn't mean it is correct". What is your opinion on this matter?

2021-03-17 05:22 UTC, tanboonji commented on src/main/java/seedu/address/logic/commands/CommandResult.java
>      private final boolean exit;
I agree with what you have said.

Will update it, push it into the branch and request for your review again later!

2021-03-17 05:41 UTC, darkdestry-t approved these changes

2021-03-17 05:51 UTC, oeiyiping commented on src/main/java/seedu/address/logic/commands/CommandResult.java
>      private final boolean exit;
Nice, LGTM now! Will be marking this conversation as resolved.

2021-03-17 05:52 UTC, oeiyiping approved these changes
LGTM.

2021-03-17 06:35 UTC, justgnohUG approved these changes
LGTM, I see the window functionality is very similar to HelpWindow.java.

2021-03-17 07:07 UTC, yaowei-soc requested changes
Changes looks good except for some minor code quality issues that I've found.

2021-03-17 07:07 UTC, yaowei-soc commented on src/main/java/seedu/address/ui/AliasWindow.java
> +    private ReadOnlyUniqueAliasMap aliases;
Can make `aliases` final

2021-03-17 07:07 UTC, yaowei-soc commented on src/main/java/seedu/address/ui/MainWindow.java
> +        }
May want to make the happy path prominent: https://nus-cs2103-ay2021s2.github.io/website/se-book-adapted/chapters/codeQuality.html#make-the-happy-path-prominent

```java
        if (helpWindow.isShowing()) {
            helpWindow.focus();
        } else {
            helpWindow.show();
        }
```

2021-03-17 07:33 UTC, tanboonji commented on src/main/java/seedu/address/MainApp.java
> +            if (!aliasesOptional.isPresent()) {
Update this in code.

2021-03-17 07:36 UTC, tanboonji commented on src/main/java/seedu/address/MainApp.java
> +            initialAliasesData = aliasesOptional.orElse(new UniqueAliasMap());
There is currently no sample or default aliases data, that is why a new UniqueAliasMap() is initialised here instead.

2021-03-17 07:43 UTC, tanboonji commented on src/main/java/seedu/address/logic/parser/AddressBookParser.java
> +    public Command parseCommand(String userInput, ReadOnlyUniqueAliasMap aliases) throws ParseException {
Added Javadoc for the ```aliases``` param.

2021-03-17 07:46 UTC, tanboonji commented on src/main/java/seedu/address/ui/MainWindow.java
> +        }
Updated this code in ```handleAlias``` and similarly for ```handleHelp```.

2021-03-17 07:47 UTC, tanboonji commented on src/main/java/seedu/address/ui/AliasWindow.java
> +    private ReadOnlyUniqueAliasMap aliases;
Updated this in code.

2021-03-17 07:49 UTC, tanboonji commented on src/main/java/seedu/address/storage/JsonAliasesStorage.java
> +        if (!jsonAliases.isPresent()) {
Updated this code.

2021-03-17 07:58 UTC, tanboonji commented on src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
> +        positions.sort((prefix1, prefix2) -> prefix1.getStartPosition() - prefix2.getStartPosition());
Updated this code.

2021-03-17 08:03 UTC, tanboonji commented on src/main/java/seedu/address/logic/parser/ParserUtil.java
> +    public static Set<Tag> parseTagsExceptLast(List<String> tags) throws ParseException {
Updated this code and added missing Javadocs for both ```parseTagsExceptLast``` and ```parseTags```.

2021-03-17 08:04 UTC, tanboonji commented on src/main/java/seedu/address/logic/parser/EditCommandParser.java
> +                userInput, PREFIX_NAME, PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS, PREFIX_TAG);
Will add this once I merge PR #77 into my branch.

2021-03-17 14:14 UTC, tanboonji commented on src/main/java/seedu/address/model/UniqueAliasMap.java
> +            throw new DuplicateAliasException();
Added Javadocs for this unchecked exception.

2021-03-17 14:14 UTC, tanboonji commented on src/main/java/seedu/address/model/UniqueAliasMap.java
> +            throw new AliasNotFoundException();
Added Javadocs for this unchecked exception.

2021-03-17 14:15 UTC, tanboonji commented on src/main/java/seedu/address/logic/parser/EditCommandParser.java
> +            return true;
Would it be okay to refactor this in Milestone 1.3? I will raise an issue after this PR is merged.

2021-03-17 14:24 UTC, yaowei-soc commented on src/main/java/seedu/address/logic/parser/EditCommandParser.java
> +            return true;
Sure!

2021-03-17 14:25 UTC, yaowei-soc commented on src/main/java/seedu/address/MainApp.java
> +            initialAliasesData = aliasesOptional.orElse(new UniqueAliasMap());
Got it, maybe later on we can implement a sample alias in

2021-03-17 14:30 UTC, yaowei-soc approved these changes

2021-03-17 15:35 UTC, merged