Replace existing search with fuzzy search
AY2021S2-CS2103T-T12-3/tp pull request #76
Opened 2021-03-15 05:42 UTC by darkdestry-t

To resolve #1 

Notable changes:
- Replace existing find command search to use fuzzy search
- Add sort order for results based on
  - First by Fuzzy similarity
  - Then by lexicographical order
- Add docs to reflect changes

@tanboonji for docs
@oeiyiping for Model and Commands
@yaowei-soc for tests

2021-03-15 09:21 UTC, tanboonji requested changes
Minor spelling mistake found. Once fixed, LGTM.

Logic component LGTM.

2021-03-15 09:21 UTC, tanboonji commented on docs/UserGuide.md
> +* Similar words are matches. e.g `Shawn` with match `Shaun`
Minor spelling mistake here. 
Should be ```matched``` instead of ```matches```.

2021-03-15 09:21 UTC, tanboonji commented on src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
> +            return matchPercentage > 60;
Would it be better if ```60``` is declared as a constant?

2021-03-15 09:55 UTC, yaowei-soc commented
Sort order for `list` changed after doing a `find` command. Should `list` command show the original order?

![sort order](https://user-images.githubusercontent.com/77482180/111135198-54042800-85b7-11eb-92db-e0a4e65cae2b.gif)

2021-03-15 18:13 UTC, yaowei-soc approved these changes
LGTM

2021-03-15 18:13 UTC, yaowei-soc commented on src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
> +    private final Logger logger = LogsCenter.getLogger(LogicManager.class);
Should be `LogsCenter.getLogger(getClass());`

2021-03-16 04:21 UTC, oeiyiping reviewed
For Model and Command: Aside from the points raised by YW and BJ, LGTM.

2021-03-17 06:00 UTC, oeiyiping approved these changes
LGTM.

2021-03-17 14:41 UTC, darkdestry-t commented on docs/UserGuide.md
> +* Similar words are matches. e.g `Shawn` with match `Shaun`
Fixed in https://github.com/AY2021S2-CS2103T-T12-3/tp/pull/76/commits/c6feea1138bcaae29f8cbfd1591ee31680590f7a

2021-03-17 14:41 UTC, darkdestry-t commented on src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
> +            return matchPercentage > 60;
Fixed in https://github.com/AY2021S2-CS2103T-T12-3/tp/pull/76/commits/c6feea1138bcaae29f8cbfd1591ee31680590f7a

2021-03-17 14:52 UTC, tanboonji approved these changes
LGTM.

2021-03-17 15:52 UTC, merged