Refactor: Add "alias" command to autocomplete list panel
AY2021S2-CS2103T-T12-3/tp pull request #95
Opened 2021-03-21 10:11 UTC by justgnohUG

Notable changes:
- Removed extra logging information
- Fix autocomplete commands does not initialize on init.

2021-03-22 15:31 UTC, yaowei-soc commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +    }
Should this test be ensuring that all items in the list starts with 'a' rather than just index 0?

2021-03-22 15:41 UTC, justgnohUG commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +    }
This test was originally to ensure the commands are sorted. Under the assumption the "add" command will always be present, regardless, the first command at index 0 should always start with a.

Perhaps a suggestion is to test every first letter of each command and see if they are alphabetical?

2021-03-22 15:45 UTC, darkdestry-t commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +    }
Do either of the following
1. Sort the collection again in the test case and compare element by element
2. Use the string comparator to compare every element with its subsequent element in a for loop

2021-03-23 06:56 UTC, justgnohUG commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +    }
Modified test case following 1.

Decided to compare element by element. 

Thank you for the suggestion.

2021-03-23 07:32 UTC, darkdestry-t requested changes

2021-03-23 07:32 UTC, darkdestry-t commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +        assertEquals(ListCommand.COMMAND_WORD, testList.get(9));
You seem to have misunderstood my approach. This is not testing the sorting order of your `getAutocompleteCommands`. This is testing the sorting order of the `Collections.sort` function.

What you should be doing is
1. get a completely clean list of command unrelated to your autocomplete command.
2. Sort that list of commands as per your expected sorting order `Collections.sort(cleanlist)`
3. Iterate through this clean sorted list and compare against your test list

This existing test will fail to achieve its purpose when
1. `logic.getAutocompleteCommand("")` returns [add, clear, alias, find, delete]
2. `Collections.sort` sorts it into the correct order
3. asserts verify that its the correct order.
4. Note that the command actually returned a bad order but all the asserts passed.

2021-03-23 08:53 UTC, justgnohUG commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +        assertEquals(ListCommand.COMMAND_WORD, testList.get(9));
I get your drift.

It was my mistake to include the Collections.sort() again right after calling the method. It is already called in getAutocompleteCommand(). 

I have implemented your suggestion 2 as per your previous comment. I am using the comparator method so the hard-coding of commands is minimized.

2021-03-23 08:57 UTC, darkdestry-t reviewed
Looks good now. Good Job

2021-03-23 08:57 UTC, darkdestry-t approved these changes

2021-03-23 09:23 UTC, yaowei-soc requested changes
Previous changes LGTM, however there might be missing test cases.

2021-03-23 09:23 UTC, yaowei-soc commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +        assertEquals(nullCommandList, emptyCommandList);
Might want to test to make sure that empty spaces returns an empty list:

[`null`, `""`]: non empty list
[`" "`, `"    "`, `"    "`]: white spaces return empty list (is this the intended behaviour?)
[`"e"`, `"ex"`, ...]: non empty list

I've also realised that the method `getAutocompleteCommands` in Logic.java isn't documented.

2021-03-23 09:52 UTC, justgnohUG commented on src/test/java/seedu/address/logic/LogicManagerTest.java
> +        assertEquals(nullCommandList, emptyCommandList);
Thank you for the spot. 

I've added a test case to handle Empty spaces / white spaces. 

Documentation for the method `getAutocompleteCommands` has been added.

2021-03-23 13:03 UTC, yaowei-soc approved these changes
LGTM

2021-03-23 16:14 UTC, merged